# 
# Synthesis run script generated by Vivado
# 

set_param simulator.modelsimInstallPath C:/Modeltech_pe_edu_10.4a/win32pe_edu
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/eleni/Documents/GitHub/TFG/Seminario 1/top.cache/wt} [current_project]
set_property parent.project_path {C:/Users/eleni/Documents/GitHub/TFG/Seminario 1/top.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo:part0:2.0 [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/eleni/Documents/GitHub/TFG/Seminario 1/top.srcs/sources_1/new/dec_7seg.vhd}
  {C:/Users/eleni/Documents/GitHub/DHD/Seminario 1/contador_8bits.vhd}
  {C:/Users/eleni/Documents/GitHub/DHD/Seminario 1/Div_frec.vhd}
  {C:/Users/eleni/Documents/GitHub/DHD/Seminario 1/top.vhd}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/eleni/Documents/GitHub/TFG/XDC master/ZYBO_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/eleni/Documents/GitHub/TFG/XDC master/ZYBO_Master.xdc}}]


synth_design -top Top -part xc7z010clg400-1


write_checkpoint -force -noxdef Top.dcp

catch { report_utilization -file Top_utilization_synth.rpt -pb Top_utilization_synth.pb }
