# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/eleni/Desktop/project_1/Encender1Led/Encender1Led.cache/wt [current_project]
set_property parent.project_path C:/Users/eleni/Desktop/project_1/Encender1Led/Encender1Led.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:2.0 [current_project]
read_verilog -library xil_defaultlib C:/Users/eleni/Desktop/project_1/Encender1Led/Encender1Led.srcs/sources_1/new/encerder1led.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/eleni/Desktop/project_1/digilent-xdc-master/Zybo-Master.xdc
set_property used_in_implementation false [get_files C:/Users/eleni/Desktop/project_1/digilent-xdc-master/Zybo-Master.xdc]


synth_design -top encerder1led -part xc7z010clg400-1


write_checkpoint -force -noxdef encerder1led.dcp

catch { report_utilization -file encerder1led_utilization_synth.rpt -pb encerder1led_utilization_synth.pb }
