# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0}]

# XDC: ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc
