# 
# Synthesis run script generated by Vivado
# 

set_param simulator.modelsimInstallPath C:/Modeltech_pe_edu_10.4a/win32pe_edu
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/eleni/Documents/GitHub/TFG/Práctica 1/ipgenerator.cache/wt} [current_project]
set_property parent.project_path {C:/Users/eleni/Documents/GitHub/TFG/Práctica 1/ipgenerator.xpr} [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo:part0:2.0 [current_project]
set_property ip_repo_paths {{c:/Users/eleni/Documents/GitHub/TFG/Práctica 1/ipgenerator.cache/ip}} [current_project]
set_property ip_output_repo {c:/Users/eleni/Documents/GitHub/TFG/Práctica 1/ipgenerator.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files {{C:/Users/eleni/Documents/GitHub/TFG/Práctica 1/datos.coe}}
read_ip -quiet {{C:/Users/eleni/Documents/GitHub/TFG/Práctica 1/ipgenerator.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/eleni/Documents/GitHub/TFG/Práctica 1/ipgenerator.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc}}]
set_property is_locked true [get_files {{C:/Users/eleni/Documents/GitHub/TFG/Práctica 1/ipgenerator.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci}}]

read_vhdl -library xil_defaultlib {
  {C:/Users/eleni/Documents/GitHub/TFG/Práctica 1/ipgenerator.srcs/sources_1/new/procesador.vhd}
  {C:/Users/eleni/Documents/GitHub/TFG/Práctica 1/ipgenerator.srcs/sources_1/new/my_scomp.vhd}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/eleni/Documents/GitHub/TFG/XDC master/ZYBO_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/eleni/Documents/GitHub/TFG/XDC master/ZYBO_Master.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top my_scomp -part xc7z010clg400-1


write_checkpoint -force -noxdef my_scomp.dcp

catch { report_utilization -file my_scomp_utilization_synth.rpt -pb my_scomp_utilization_synth.pb }
