# 
# Synthesis run script generated by Vivado
# 

set_param simulator.modelsimInstallPath C:/Modeltech_pe_edu_10.4a/win32pe_edu
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/eleni/Documents/GitHub/TFG/Practica 2/Practica 2.cache/wt} [current_project]
set_property parent.project_path {C:/Users/eleni/Documents/GitHub/TFG/Practica 2/Practica 2.xpr} [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo:part0:2.0 [current_project]
add_files -quiet {{c:/Users/eleni/Documents/GitHub/TFG/Practica 2/Practica 2.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp}}
set_property used_in_implementation false [get_files {{c:/Users/eleni/Documents/GitHub/TFG/Practica 2/Practica 2.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp}}]
read_vhdl -library xil_defaultlib {
  {C:/Users/eleni/Documents/GitHub/TFG/Practica 2/controlador_vga_640_x_480_60.vhd}
  {C:/Users/eleni/Documents/GitHub/TFG/Practica 2/bola.vhd}
  {C:/Users/eleni/Documents/GitHub/TFG/Practica 2/vga_top.vhd}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/eleni/Documents/GitHub/TFG/XDC master/ZYBO_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/eleni/Documents/GitHub/TFG/XDC master/ZYBO_Master.xdc}}]


synth_design -top vga_top -part xc7z010clg400-1


write_checkpoint -force -noxdef vga_top.dcp

catch { report_utilization -file vga_top_utilization_synth.rpt -pb vga_top_utilization_synth.pb }
